{% set name = "squarify" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54091f6ad175f7f201f8934574e647ce1b50dedc478c5fd968688eb7d7469f95

build:
  number: 0
  skip: true # [py>=36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Note this isn't explicitly called out in setup.py but matplotlib is imported
    # https://github.com/laserson/squarify/blob/42e332c9c69146fcb3bda44c1d3cc3009955327c/squarify/__init__.py#L222
    - matplotlib-base

test:
  imports:
    - squarify

about:
  home: https://github.com/laserson/squarify
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'Pure Python implementation of the squarify treemap layout algorithm.'

  description: 'Pure Python implementation of the squarify treemap layout algorithm.'
  doc_url: https://github.com/laserson/squarify
  dev_url: https://github.com/laserson/squarify

extra:
  recipe-maintainers:
    - aaronmussig
